FROM python:3.11-slim

WORKDIR /app

COPY requirements-automation.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY topics_local.py .
COPY automation.py .

CMD ["python", "automation.py"]
