FROM python:3.11-slim

WORKDIR /app

COPY requirements-ingestor.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY topics_local.py .
COPY ingestor.py .

CMD ["python", "ingestor.py"]
